version: '3.0'

services:
  angular:
    build: client
    ports:
      - '4200:4200'

  express:
    build: .
    ports:
      - '5000:5000'
    links:
      - mongodb
    
  mongodb:
    image: mongo
    ports:
       - '27017:27017'